Ac mane page layout
losyh/Api-console pull request #3
Opened 2024-01-08 07:01 UTC by losyh

2024-01-08 13:39 UTC, midorun requested changes

2024-01-08 13:39 UTC, midorun commented on src/containers/MainPage.js
> +    let server = [
const server...
и нам не нужно держать константы внутри функции, вынеси массив за функцию MainPage

2024-01-09 09:10 UTC, losyh commented on src/containers/MainPage.js
> +import { Wrapper } from './LoginPage';
Устранено

2024-01-09 09:10 UTC, losyh commented on src/containers/LoginPage.js
> +export const Wrapper = styled.div`
Устранено

2024-01-09 09:10 UTC, losyh commented on src/containers/MainPage.js
>  display: inline-flex;
Устранено

2024-01-09 09:13 UTC, losyh commented on src/containers/MainPage.js
> +const HeaderDiv = styled.div`
Заменил на HeaderSection, так же можно?

2024-01-09 15:50 UTC, losyh commented on src/containers/MainPage.js
>  const FullScreenStyled = styled.img`
Устранено

2024-01-09 15:50 UTC, losyh commented on src/containers/MainPage.js
> +const DivItem = styled.div`
Устранено

2024-01-09 15:51 UTC, losyh commented on src/containers/MainPage.js
> +const Rectangle = styled.div`
Добавил через Border. Прошлый компонент удалил

2024-01-09 15:52 UTC, losyh commented on src/containers/MainPage.js
> +    let server = [
Вынес, ошибку понял

2024-01-09 15:52 UTC, losyh commented on src/containers/MainPage.js
> +                </HistoryTrackItem>
Готов на созвон

2024-01-10 22:19 UTC, midorun commented on src/containers/LoginPage/LoginPage.js
> +      <Styled.Input id={label} type={type} $inputBorderError={error} $inputBoxShadowError={error}/>
Обычно просто передают флаг отвечающий за ошибку
По сути для Styled.Label, Styled.Input, важен сам факт наличия/отсутсвия ошибки. 

Я бы просто оставил error, не вижу смысла в лишних переменных

2024-01-11 11:57 UTC, losyh commented on src/containers/LoginPage/LoginPage.js
> +      <Styled.Input id={label} type={type} $inputBorderError={error} $inputBoxShadowError={error}/>
Согласен, ошибку понял, устранено

2024-01-21 17:35 UTC, midorun commented on src/containers/MainPage/Header/styled.js
> +flex-direction: row;
Насколько я помню это дефолтное значение, можем не указывать

2024-01-21 17:44 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +        });
Забыл убрать eventListener. Пример в HistoryTrackItem

2024-01-21 17:47 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    const onChangeRequestItems = (items) => {
Бессмысленная функция, почему бы сразу не прокидывать ниже setRequestItems. Более того даже путает немного, onChange в основной массе значит взаимодействие с инпутами

2024-01-21 17:49 UTC, midorun commented on src/containers/MainPage/Header/styled.js
> +font-weight: 400;
дефолтные значения, если их убрать ничего не поменяется

2024-01-21 17:53 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    const onDeleteAllItems = () => {
Не замечание, просто для "подумать"

Я внутренние функции компонента называю без on, чтобы отличать их от тех, что пришли через пропсы, то есть в HistoryTrack

deleteAllItems

А в historyTrackItems onDeleteAllItems

2024-01-21 17:54 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +        const scrollContainer = document.getElementById("scroll");
заменить на ref, если не понял как, напишешь, на созвоне обсудим

2024-01-21 17:56 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItems.js
> +    const generateMocks = (count) => {
Вынести из компонента, при ререндере, функция каждый раз будет заново создаваться. - это не нам не нужно

2024-01-21 17:58 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItems.js
> +    useEffect(() => {
в historyTrack вне компонента создавать константу и кидать ее в useState() как дефолтное значение


const defaultRequestItems = generateMocks(15)

const HistoryTrack = () => {

    const [requestItems, setRequestItems] = useState(defaultRequestItems);

2024-01-21 17:59 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItems.js
> +const HistoryTrackItems = (props) => {
деструктуризируй пропсы, не надо обращаться через props.variable
дублируется props много раз

2024-01-21 18:01 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItems.js
> +        }))
На будущее, передачу пропсов можно сделать через rest

<HistoryTrackItem key={index} {...item} onDeleteItem={() => onDeleteItem(index)}/>

2024-01-21 18:02 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +    const myRef = useRef(null)
historyItemRef

2024-01-21 18:03 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +    const OnCopy = (item) => {
с маленькой буквы

2024-01-22 14:06 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +    document.body.appendChild(node)
зачем создавать div? Почему сразу не можем в body кидать children?
https://react.dev/reference/react-dom/createPortal

2024-01-22 14:10 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +    const handleClickCopy = () => {
вынеси функцию на уровень выше, она каждый раз будет создаваться при создании dropdown, таких вещей стоит избегать

2024-01-22 14:12 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +        <Styled.DropDownItem $background={'var(--Red, #CF2C00)'}  onClick={() => props.onDeleteItem()}>Удалить</Styled.DropDownItem>
handleClickCopy передаешь напрямую, а onDeleteItem через коллбэк, у обеих функций сигнатура идентична, вызываешь по разному. Почему?

2024-01-23 08:18 UTC, losyh commented on src/containers/MainPage/Header/styled.js
> +flex-direction: row;
Да, верно. Убрал   align-items: center и flex-direction: row

2024-01-23 08:20 UTC, losyh commented on src/containers/MainPage/Header/styled.js
> +export const LogoStyled = styled.img`
Устранено. Это осталось со старого шаблона, не заметил.

2024-01-23 08:23 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +        });
Устранено. Насколько это критичный момент? На созвоне спрошу, если не забуду.

2024-01-23 08:28 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    const onChangeRequestItems = (items) => {
Устранено. До сих пор в голове шаблон ES6 стандарта с классовыми компонентами. Буду иметь ввиду.

2024-01-23 08:30 UTC, losyh commented on src/containers/MainPage/Header/styled.js
> +font-weight: 400;
Устранено. Буду обращать внимание.

2024-01-23 09:01 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    const onDeleteAllItems = () => {
Устранил. Думаю, хорошее правило.

2024-01-23 09:02 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItems.js
> +    const generateMocks = (count) => {
Вынес. Ошибку понял.

2024-01-23 09:21 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItems.js
> +    useEffect(() => {
Устранил.

2024-01-23 09:38 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItems.js
> +const HistoryTrackItems = (props) => {
Исправил везде,где заметил.

2024-01-23 09:42 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +    const myRef = useRef(null)
Переименовал

2024-01-23 09:42 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +    const OnCopy = (item) => {
Убрал

2024-01-23 09:49 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +    document.body.appendChild(node)
Исправлено

2024-01-23 09:55 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +    const handleClickCopy = () => {
Перенес на уровень выше в HistoryTrackItem. но не совсем понял зачем это, если в таком случае функция будет создаваться при рендере HistoryTrackItem

2024-01-23 09:57 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrackItems/HistoryTrackItem/HistoryTrackItem.js
> +        <Styled.DropDownItem $background={'var(--Red, #CF2C00)'}  onClick={() => props.onDeleteItem()}>Удалить</Styled.DropDownItem>
Устранил. Потому что в первоначальной версии помещал в функцию onDeleteItem индекс, потом исправил на текущий вариант, а вызов через колбек просто не изменил

2024-01-23 16:22 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +        const scrollContainer = document.getElementById("scroll");
Не разобрался, завтра тогда на созвоне

2024-01-24 09:35 UTC, midorun commented on package.json
> +    "prettier": "2.0.5",
не знаю сам догадался или по гайду, но то что ты эти пакеты поместил в devDependencies - молодец. 

В depencencies хранятся пакеты с непосрдественно рабочим кодом, который физически на проект влияет (всякие библиотеки компонентов, react, redux и тд) , а прочие утилитарные штуки храним в devDependencies

2024-01-24 09:37 UTC, midorun commented on src/containers/MainPage/Header/Header.js
> +        <Styled.LogOut src="/icons/log-out.svg" />
Эти компоненты нужно положить в один контейнер, в будущем тебе придется только на один элемент вешать handler по которому будет происходить выход из приложение и пользователю будет легче попасть по такому элементу

2024-01-24 09:38 UTC, midorun commented on src/containers/MainPage/Header/styled.js
> +export const FullScreenStyled = styled.img`
Для справки, кликабельным иконкам, да и больше части элементов, делают небольшой padding, чтобы "раздуть" компонент, опять же, чтобы по нему было легче попасть

2024-01-24 09:38 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +const defaultRequestItems = generateMocks(12);
супер

2024-01-24 09:41 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    });
Проверь правильность синтаксиса использования "отчистки/cleanup" в useEffect
https://react.dev/reference/react/useEffect#reference

2024-01-24 09:53 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    const scrollContainer = document.getElementById('scroll');
Сделать по аналогии с HistoryTrackItem, там использовал ref, тут зачем-то полез в DOM через getElementById

2024-01-24 16:05 UTC, losyh commented on src/containers/MainPage/Header/Header.js
> +        <Styled.LogOut src="/icons/log-out.svg" />
Устранено

2024-01-24 16:05 UTC, losyh commented on src/containers/MainPage/Header/styled.js
> +export const FullScreenStyled = styled.img`
Раздул все иконки в MainPage

2024-01-24 16:08 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    const scrollContainer = document.getElementById('scroll');
Потому что я рот ебал этих рефоф

2024-01-24 16:10 UTC, midorun commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    const scrollContainer = document.getElementById('scroll');
Аргумент, закрываю коммент

2024-01-25 11:57 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    });
Устранено

2024-01-25 11:57 UTC, losyh commented on src/containers/MainPage/HistoryTrack/HistoryTrack.js
> +    const scrollContainer = document.getElementById('scroll');
Устранено

2024-01-25 12:02 UTC, merged